# These are supported funding model platforms

github: # seamusrobertmurphy
custom: # https://winrock.org/winrock-joins-consortium-to-help-mobilize-finance-to-reduce-emissions-from-deforestation-and-forest-degradation/
